AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
      AWS Athena geospatial UDFs for selected h3-java https://github.com/uber/h3-java 
      functions. See the API documentation at https://daniel-cortez-stevenson.github.io/aws-athena-udfs-h3
Metadata:
  'AWS::ServerlessRepo::Application':
    Name: aws-athena-udfs-h3
    Description: >
      AWS Athena geospatial UDFs for selected h3-java https://github.com/uber/h3-java 
      functions. See the API documentation at https://daniel-cortez-stevenson.github.io/aws-athena-udfs-h3
    Author: Daniel Cortez Stevenson
    SpdxLicenseId: Apache-2.0
    LicenseUrl: LICENSE.txt
    ReadmeUrl: README.md
    Labels:
      - athena-federation
      - h3
      - athena-udfs
      - geospatial
    HomePageUrl: https://github.com/daniel-cortez-stevenson/aws-athena-udfs-h3
    SemanticVersion: 1.0.0-rc7
    SourceCodeUrl: https://github.com/daniel-cortez-stevenson/aws-athena-udfs-h3
Parameters:
  LambdaFunctionName:
    Type: String
    Description: The name of Lambda function, which calls the H3AthenaUDFHandler
    Default: h3-athena-udf-handler
    AllowedPattern: ^[a-z0-9-_]{1,64}$
  LambdaTimeout:
    Type: Number
    Description: Maximum Lambda invocation runtime in seconds
    Default: 300
    MinValue: 1
    MaxValue: 900
  LambdaMemory:
    Type: Number
    Description: Lambda memory in MB
    Default: 3008
    MinValue: 128
    MaxValue: 10240
Resources:
  H3AthenaUDFHandler:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: !Ref LambdaFunctionName
      Handler: io.jyde.aws.athena.connectors.udf.h3.H3AthenaUDFHandler
      Runtime: java8
      CodeUri: ./target/aws-athena-udfs-h3-1.0.0-rc7-SNAPSHOT.jar
      Description: >
        AWS Athena geospatial UDFs for selected h3-java https://github.com/uber/h3-java 
        functions. See the API documentation at https://daniel-cortez-stevenson.github.io/aws-athena-udfs-h3
      MemorySize: !Ref LambdaMemory
      Timeout: !Ref LambdaTimeout
