AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  This connector extends Amazon Athena's capability by adding UDFs (via Lambda) for selected
  [h3-java](https://github.com/uber/h3-java) Java functions to support geospatial indexing and queries with Uber's
  [H3](https://h3geo.org/)
Metadata:
  'AWS::ServerlessRepo::Application':
    Name: aws-athena-udfs-h3
    Description: >
      This connector extends Amazon Athena's capability by adding UDFs (via Lambda) for selected
      [h3-java](https://github.com/uber/h3-java) Java functions to support geospatial indexing and queries with Uber's
      [H3](https://h3geo.org/)
    Author: Daniel Cortez Stevenson
    SpdxLicenseId: Apache-2.0
    LicenseUrl: LICENSE.txt
    ReadmeUrl: README.md
    Labels:
      - athena-federation
      - h3
      - athena-udfs
      - geospatial
    HomePageUrl: https://github.com/daniel-cortez-stevenson/aws-athena-udfs-h3/blob/main/aws-athena-udfs-h3
    SemanticVersion: 0.0.1
    SourceCodeUrl: https://github.com/daniel-cortez-stevenson/aws-athena-udfs-h3/blob/main/aws-athena-udfs-h3
Parameters:
  LambdaFunctionName:
    Type: String
    Description: The name of Lambda function, which calls the H3AthenaUDFHandler
    Default: h3-athena-udf-handler
    AllowedPattern: ^[a-z0-9-_]{1,64}$
  LambdaTimeout:
    Type: Number
    Description: Maximum Lambda invocation runtime in seconds
    Default: 300
    MinValue: 1
    MaxValue: 900
  LambdaMemory:
    Type: Number
    Description: Lambda memory in MB
    Default: 3008
    MinValue: 128
    MaxValue: 10240
Resources:
  H3AthenaUDFHandler:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: !Ref LambdaFunctionName
      Handler: io.jyde.aws.athena.connectors.udf.h3.H3AthenaUDFHandler
      Runtime: java8
      CodeUri: ./target/aws-athena-udfs-h3-1.0.jar
      Description: >
        This connector extends Amazon Athena's capability by adding UDFs (via Lambda) for selected
        [h3-java](https://github.com/uber/h3-java) Java functions to support geospatial indexing and queries with Uber's
        [H3](https://h3geo.org/)
      MemorySize: !Ref LambdaMemory
      Timeout: !Ref LambdaTimeout
